---
- hosts: "{{targets}}"
  become: yes
  gather_facts: no
  tasks:
  - name: "Issue the necessary commands!"
    ios_command:
      commands: "{{tshoot_commands}}"
    register: output
  - name: "Save output to {{tshoot_path}}"
    copy:
      content: "{{output.stdout}}"
      dest: "{{tshoot_path}}"
    delegate_to: localhost
