---
- hosts: ubuntu
  become: yes
  gather_facts: no
  tasks:
  - name: "Install apache2!"
    apt:
      name: apache2
      state: latest
    notify:
      - "enable apache"
      - "start apache"
  - name: "Check apache2!"
    uri:
      url: "http://{{inventory_hostname}}"
    delegate_to: localhost
  handlers:
  - name: enable apache
    systemd:
      name: apache2
      enabled: yes
  - name: start apache
    service:
      name: apache2
      state: restarted