---
- hosts: 2019A
  become: no
  gather_facts: no
  tasks:
  - name: "Download Chrome Installer!"
    win_get_url:
      url: https://dl.google.com/tag/s/appguid%3D%7B8A69D345-D564-463C-AFF1-A69D9E530F96%7D%26iid%3D%7B3FE8352F-E9BC-84CA-00EA-80E31FCFFEB2%7D%26lang%3Dhu%26browser%3D4%26usagestats%3D1%26appname%3DGoogle%2520Chrome%26needsadmin%3Dprefers%26ap%3Dx64-stable-statsdef_1%26installdataindex%3Dempty/chrome/install/ChromeStandaloneSetup64.exe
      dest: c:\temp\ChromeStandaloneSetup64.exe
  - name: "Invoke the installer!"
    win_package:
      path: c:\\temp\\ChromeStandaloneSetup64.exe
      product_id: '{7B3FE8352F-E9BC-84CA-00EA-80E31FCFFEB2}'
      wait: yes