---
- hosts: cisco
  become: yes
  gather_facts: no
  tasks:
  - name: "Issue the necessary commands!"
    ios_command:
      commands:
        - "show version"
        - "show ip int brief"
        - "show run"
    register: output
  - name: "See what's inside!"
    debug:
      msg: "{{output.stdout}}"
  - name: "Save output to /tmp/{{inventory_hostname}}_tshoot.txt"
    copy:
      content: "{{output.stdout}}"
      dest: /tmp/{{inventory_hostname}}_tshoot.txt
    delegate_to: localhost