---
- hosts: cisco
  become: yes
  gather_facts: no
  tasks:
  - name: "Configure c7200"
    ios_config:
      lines:
        - standby 1 ip 192.168.56.100
        - standby priority 100
        - standby 1 preempt
      parents: int fa0/0
    when: inventory_hostname == 'c7200'
  - name: "Configure c72002"
    ios_config:
      lines:
        - standby 1 ip 192.168.56.100
        - standby 1 preempt
      parents: int fa0/0
    when: inventory_hostname == 'c72002'