---
- hosts: ubuntu
  become: yes
  gather_facts: no
  tasks:
  - name: "Copy app.py"
    copy:
      src: app.py
      dest: /tmp/app.py
  - name: "Copy Dockerfile"
    copy:
      src: Dockerfile
      dest: /tmp/Dockerfile
  - name: "Build the container"
    docker_image:
      name: webapp
      build:
        path: /tmp/
      source: build
  - name: "Run the webapp"
    docker_container:
      name: webapp
      image: webapp
      state: started
      ports:
        - "9999:9999"