---                                                
- hosts: 2019A                                     
  become: no                                       
  gather_facts: no                                 
  tasks:                                           
  - name: "Provision user {{item}}!"               
    win_user:                                      
      name: "{{item}}"                             
      password: Start!123                          
      state: present                               
      groups:                                      
        - Users                                    
    with_items: "{{default_users}}"                